name: pathfinder
channels:
  - conda-forge
dependencies:
  - python==3.13  
  - sys
  - pyrpca
  - numpy
  - numba
  - shapely
  - cartopy
  - scikit-image
  - pandas
  - matplotlib
  - scipy
  - pyproj
  - tqdm
  - datetime